# Default values for mccs (aavs-system)
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

system: SW-infrastructure
subsystem: aavs-system
telescope: SKA-low

labels:
  app: ska-aavs-system

global:
  minikube: true
  tango_host: databaseds-tango-base:10000
  cluster_domain: cluster.local

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.1
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 20m
    memory: 50Mi

image:
  registry: artefact.skao.int
  name: ska-aavs-system
  tag: 0.1.0
  pullPolicy: IfNotPresent
