# Observation-related configuration, specifying the channel region
# for the station beamformer
observation:
    start_frequency_channel: 75e6
    bandwidth: 6.25e6

# Station configuration parameters
station:
    id: 0
    name: "Malta"
    channel_truncation: 3
    beam_integration_time: 1
    channel_integration_time: 1
    beamformer_scaling: 4
    bitfile: "/home/lessju/Software/aavs-system/bitfiles/itpm_v1_1_tpm_test_wrap_sbf405_01021793.bit"
    default_preadu_attenuation: -1
    equalize_preadu: No
    use_internal_pps: True

# Network configuration parameters
network:
    lmc:
        lmc_mac: 0x54b20393d202
        lmc_ip: "10.0.10.10"
        lmc_port: 4660
        tpm_cpld_port: 10000
        use_teng: False
        
        # Integrated data configuration
        integrated_data_port: 5000
        integrated_data_ip: "10.0.10.10"
        use_teng_integrated: False

    csp_ingest:
        dst_mac: 0x5065F385AC71  # 40Gb MAC
        dst_ip: "10.0.0.100"  # 40Gb MAC
        dst_port: 4660
        src_mac: Null
        src_ip: 10.0.0.99
        src_port: Null

# List of TPM IPs (or names) which will form station
tiles:
    - 10.0.10.2
