# Observation-related configuration, specifying the channel region
# for the station beamformer
observation:
    start_frequency_channel: 156.25e6 #50e6 #75e6 #
    bandwidth: 6.25e6 #300e6 #6.25e6 #

# Station configuration parameters
station:
    id: 0
    channel_truncation: 5
    beam_integration_time: 1
    channel_integration_time: 1
    beamformer_scaling: 4
    bitfile: "/opt/aavs/bitfiles/itpm_v1_5_tpm_test_wrap_sbf416.bit"

    equalize_preadu: No
    pps_delays: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Network configuration parameters
network:
    lmc:
        lmc_mac: None
        lmc_ip:  "10.0.10.40"
        lmc_port: 4660
        tpm_cpld_port: 10000
        use_teng: True

        integrated_data_ip: "10.0.10.40"
        integrated_data_port: 4660
        use_teng_integrated: True

    csp_ingest:
        dst_mac: None
        dst_ip: "10.0.10.40"
        dst_port: 4660
        src_mac: Null
        src_ip: Null
        src_port: Null

# List of TPM IPs (or names) which will form station
tiles:
    - "10.0.10.71"
#    - "10.0.10.72"
#    - "10.0.10.73"
#    - "10.0.10.74"
    - "10.0.10.75"
#    - "10.0.10.76"
#    - "10.0.10.77"
#    - "10.0.10.78"

